on: [push]

jobs:
  soos:
    permissions:
      security-events: write # for uploading code scanning alert info
    name: SOOS SAST Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run SOOS DAST analysis testing
        uses: soos-io/soos-dast-github-action@fix/PA-12859 
        with:
          client_id: ${{ secrets.QA_SOOS_CLIENT_ID }}
          api_key: ${{ secrets.QA_SOOS_API_KEY }}
          target_url: "https://brokencrystals.com/"
          project_name: ${{ github.repository }}
          api_url: "https://qa-api.soos.io/api/"
          verbose: "true"
          scan_mode: "baseline"
          request_headers: "headerTestA:a,headerTestB:b"

