on: [push]

jobs:
  soos:
    name: SOOS SAST Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run SOOS DAST analysis testing
        uses: soos-io/soos-dast-github-action@v2.4.0
        with:
          client_id: ${{ secrets.QA_SOOS_CLIENT_ID }}
          api_key: ${{ secrets.QA_SOOS_API_KEY }}
          #scan_mode: "baseline"
          #api_scan_format: "soap"
          target_url: https://brokencrystals.com/
          #target_url: "https://www.dataaccess.com/webservicesserver/NumberConversion.wso"
          project_name: 'dast-githubActions-26'
          image_tag: beta
          #project_name: ${{ github.repository }}
          #request_eeaders: "invalid"
          api_url: "https://qa-api.soos.io/api/"
          oauthParameters: "paramA, paramB"
          oauthTokenUrl: "https://oauth.example/token"
          #verbose: "true"
          #debug: "false"
          #other_options: "-d"          
          #output_format: "SARIF"
          #disable_rules: "10003,10010,10011,10020,10110"
