on: [push]

jobs:
  synchronous-analysis-with-blocking-result:
    name: SOOS SAST Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run SOOS DAST analysis testing
        uses: soos-io/soos-dast-github-action@fix/PA-12446
        with:
          client_id: ${{ secrets.QA_SOOS_CLIENT_ID }}
          api_key: ${{ secrets.QA_SOOS_API_KEY }}
          target_url: "https://brokencrystals.com/"
          project_name: "PA-12446 Test"
          api_url: "https://qa-api.soos.io/api/"
          verbose: "true"
          output_format: "sarif"
      - name: Upload SOOS DAST SARIF Report
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: results.sarif
