on: [push]

jobs:
  soos_sbom_analysis_example:
    name: SOOS SBOM Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - uses: actions/checkout@master
      - name: Run SOOS SBOM Scan
        uses: soos-io/soos-sbom-github-action@v1 # GET Latest Version from https://github.com/marketplace/actions/soos-sbom
        with:
          client_id: ${{ secrets.SOOS_CLIENT_ID }}
          api_key: ${{ secrets.SOOS_API_KEY }}
          #api_url: 'https://qa-api.soos.io/api/'
          project_name: "SBOM Github Actions Test"
          sbom_path: "sbom-files/indico_v3.2.8.python.cdx.json"          
          log_level: INFO
          #sbom_version: 1.2.1-pre.1
          #output_format: SARIF
          #comment
