on: [push]

jobs:
  soos:
    name: SOOS SAST Scan
    runs-on: ubuntu-latest
    steps:
      - name: SOOS DAST Analysis
        uses: soos-io/soos-dast-github-action@v2
        with:
           image_tag: alpha
           client_id: ${{ secrets.QA_SOOS_CLIENT_ID }}
           api_key: ${{ secrets.QA_SOOS_API_KEY }}
           api_url: "https://qa-api.soos.io/api/"
           project_name: "github-dast-auth-3"
           target_url: "https://demoqa.com/profile"
           auth_username: "testfer2"
           auth_password: "Testfer2022#"
           auth_login_URL: "https://demoqa.com/login"
           auth_username_field: "userName"
           auth_password_field: "password"
           auth_submit_field: "login"
           auth_target_url: "https://demoqa.com/Account/v1/User/1cba41e9-0e7e-4c53-8476-6cc33e84eaf7"
           log_level: "DEBUG"
