on: [push]

jobs:
  soos:
    permissions:
      security-events: write # for uploading code scanning alert info
    name: SOOS SAST Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run SOOS DAST analysis testing
        uses: soos-io/soos-dast-github-action@v2
        with:
          client_id: ${{ secrets.QA_SOOS_CLIENT_ID }}
          api_key: ${{ secrets.QA_SOOS_API_KEY }}
          scan_mode: "baseline"
          #api_scan_format: "invalid"
          target_url: "https://brokencrystals.com/"
          project_name: ${{ github.repository }}
          api_url: "https://qa-api.soos.io/api/"
          verbose: "true"
          #debug: "false"
          #other_options: "-d"          
          request_headers: "headerTestA:a,headerTestB:b"
          request_cookies: "cookie1:a,cookie2:b"
          bearer_token: "invalidValue"
          
