on: [push]

jobs:
  soos_sast_scan:
    name: SOOS SAST Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: actions/checkout@master
      - name: Run SOOS SAST Analysis
        uses: soos-io/soos-sast-github-action@v1 # GET Latest Version from https://github.com/marketplace/actions/soos-sast
        with:
          client_id: ${{ secrets.QA_SOOS_CLIENT_ID }}
          api_key: ${{ secrets.QA_SOOS_API_KEY }}
          api_url: "https://qa-api.soos.io/api/"
          project_name: "SAST Github Actions Test 13"
          sast_version: 1.0.4-pre.1
          #sast_path: "../../"
          #directories_to_exclude: "ProjectB/sarif-files/**" 
          #files_to_exclude: "**/sarif-files/image_resizer_semgrep_output.sarif.json"
          #branch_name: 'regression-test'
          #build_version: '1.0.0'
          #log_level: INFO  
          verbose: true
          #on_failure: continue_on_failure
