on: [push]

jobs:
  soos:
    name: SOOS SAST Scan
    runs-on: ubuntu-latest
    steps:
      - name: SOOS DAST Analysis
        uses: soos-io/soos-dast-github-action@8c729d97193aa72d55fd3e1320e4b8986386323b
        with:
           image_tag: beta
           client_id: ${{ secrets.SOOS_QA_CLIENT_ID }}
           api_key: ${{ secrets.SOOS_QA_API_KEY }}
           project_name: "dast-githubActions-11"
           api_url: "https://qa-api.soos.io/api/"
           target_url: "https://test-dast-auth-2b2b4f2c2fc0.herokuapp.com"
           auth_username: test-dast-11@tester.com
           auth_password: "invalidPassword"
           auth_submit_field: '/html/body/div/main/section/div/div[2]/div/form/div[2]/button'
           auth_login_url: "https://test-dast-auth-2b2b4f2c2fc0.herokuapp.com/login"
           auth_verification_url: "https://test-dast-auth-2b2b4f2c2fc0.herokuapp.com/profile"
           on_failure: "continue_on_failure"
           log_level: "DEBUG"
