on: [push]

jobs:
  soos_sbom_analysis_example:
    name: SOOS SBOM Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: actions/checkout@master
      - name: Run SOOS SBOM Scan
        uses: soos-io/soos-sbom-github-action@v1 # GET Latest Version from https://github.com/marketplace/actions/soos-sbom
        with:
          client_id: ${{ secrets.PD_SOOS_CLIENT_ID }}
          api_key: ${{ secrets.PD_SOOS_API_KEY }}
          #api_url: 'https://qa-api.soos.io/api/'
          project_name: "SBOM Github Actions Test"
          sbom_path: "sbom-files"          
          log_level: DEBUG
          #sbom_version: 1.0.0-pre.11
          #output_format: SARIF
