on: [push]
 
jobs:
  soos_dast_analysis_example:
    name: SOOS DAST Analysis Example
    runs-on: ubuntu-latest
    steps:
      - name: Run SOOS DAST Analysis
        uses: soos-io/soos-dast-github-action@v1
        with:
          client_id: ${{ secrets.SOOS_CLIENT_ID }}
          api_key: ${{ secrets.SOOS_API_KEY }}
          project_name: "GitHub Actions - DAST"
          scan_mode: "baseline" # "baseline", fullscan, or apiscan
          #apiscan_format: 'openapi' # Mandatory if you select apiscan mode 
          api_url: "https://qa-api.soos.io/api/"
          target_url: "https://brokencrystals.com/"
          sarif: true
          gpat: ${{ secrets.SOOS_GITHUB_PAT }}