name: Example workflow using SOOS
# Events required to engage workflow (add/edit this list as needed)
on: push
jobs:
  soos-sca-analysis:
    name: SOOS SCA Scan
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/setup-node@v4
      with:
        node-version: 20
    - uses: actions/checkout@master
    - name: Run SOOS - Scan for vulnerabilities
      uses: soos-io/soos-sca-github-action@v2
      with:
        project_name: ${{ github.repository }}
        #api_url: "https://qa-api.soos.io/api/"
        # Visit https://soos.io to get the required tokens to leverage SOOS scanning/analysis services
        client_id: ${{ secrets.PD_SOOS_CLIENT_ID }}
        api_key: ${{ secrets.PD_SOOS_API_KEY }}
        #script_version: 4.0.8-pre.3
        #package_managers: 'Swift'
        #log_level: DEBUG
        output_format: 'sarif'
    - name: Upload SOOS SARIF Report
      uses: github/codeql-action/upload-sarif@v3
      with:
          sarif_file: results.sarif
