name: "SOOS DAST Scan"

on: [push]

jobs:
  soos:
    permissions:
      security-events: write # for uploading code scanning alert info
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    name: SOOS DAST Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Run SOOS DAST Analysis
        uses: soos-io/soos-dast-github-action@8c729d97193aa72d55fd3e1320e4b8986386323b
        with:
          client_id: ${{ secrets.QA_SOOS_CLIENT_ID }}
          api_key: ${{ secrets.QA_SOOS_API_KEY }}
          project_name: "DAST_gha_test - case 25"
          #project_name: "DAST - GitHub Actionst"
          scan_mode: "baseline"
          target_url: "https://brokencrystals.com/"
          api_url: "https://qa-api.soos.io/api/"
          export_format: "Sarif"
          export_file_type: "Json"
          other_options: "-d"
          #disable_rules: "10003,10010,10011,10020,10021,10110"
          image_tag: alpha
          log_level: DEBUG           


