name: "SOOS DAST Scan"

on: [push]

jobs:
  soos:
    permissions:
      security-events: write # for uploading code scanning alert info
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    name: SOOS DAST Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Run SOOS DAST Analysis
        uses: soos-io/soos-dast-github-action@v2.4.0
        with:
          client_id: ${{ secrets.QA_SOOS_CLIENT_ID }}
          api_key: ${{ secrets.QA_SOOS_API_KEY }}
          #project_name: "DAST_gha_test - case 26 - 27"
          project_name: "GitHub Actions"
          scan_mode: "baseline"
          target_url: "https://brokencrystals.com/"
          api_url: "https://qa-api.soos.io/api/"
          export_format: "Sarif"
          export_file_type: "Json"
          other_options: "-d"
          disable_rules: "10003,10010,10011,10020,10021,10110"
          image_tag: alpha

      - uses: actions/checkout@master
      - name: Run SOOS SCA Analysis
        uses: soos-io/soos-sca-github-action@v2
        with:
          client_id: ${{ secrets.QA_SOOS_CLIENT_ID }}
          api_key: ${{ secrets.QA_SOOS_API_KEY }}
          api_url: "https://qa-api.soos.io/api/"
          project_name: "GitHub Actions"
          #export_format: "sarif"
          #export_file_type: "json"
          sca_version: latest
          #log_level: DEBUG 
          
      - name: Find and rename SARIF file since it is unique
        run: |
          file=$(find . -name "*.sarif.json" | head -n 1)
          if [ -n "$file" ]; then
            mv "$file" output.sarif.json
            echo "Renamed $file to output.sarif.json"
          else
            echo "No SARIF file found" && exit 1
          fi
      - name: Upload SOOS DAST SARIF Report
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: output.sarif.json

